import { communityHeader } from '../js/community-shell.js';

// Product preview only. All community records and changes are synthetic,
// held in memory, and reset on reload. No Firebase, network or browser storage.
const families = [
  {id:'f1',name:'The Island Explorers',area:'Lamai',ages:'4–7',approach:'Nature & projects',tags:['Nature','Art','Beach science'],initial:'I',color:'lime',about:'Outdoor discoveries, simple creative projects and relaxed afternoons together.'},
  {id:'f2',name:'The Creative Collective',area:'Bophut',ages:'6–10',approach:'Mixed approaches',tags:['Music','Making','Stories'],initial:'C',color:'peach',about:'A sample family looking for music, storytelling and hands-on making with friends.'},
  {id:'f3',name:'The Curious Readers',area:'Maenam',ages:'4–7',approach:'Montessori inspired',tags:['Books','Nature','Building'],initial:'R',color:'lilac',about:'Practical learning, quiet reading corners and discovering the island at a gentle pace.'},
  {id:'f4',name:'The Little Makers',area:'Lamai',ages:'6–10',approach:'Nature & projects',tags:['Making','Science','Building'],initial:'M',color:'peach',about:'A fictional family interested in small group science and creative problem-solving.'}
];
const events = [
  {id:'e1',name:'Beach explorers',area:'Lamai',topic:'Nature',time:'Sample Saturday · 9:00–10:30',ages:'4–7',capacity:8,joined:4,icon:'☀',color:'lime',about:'Notice shells, sketch the shoreline and build a shared nature map. Caregivers take part.'},
  {id:'e2',name:'Make a little music',area:'Bophut',topic:'Creative',time:'Sample Sunday · 10:00–11:00',ages:'4–10',capacity:10,joined:7,icon:'♫',color:'peach',about:'A gentle rhythm and song circle with everyday instruments. Caregivers take part.'},
  {id:'e3',name:'Build, test, try again',area:'Maenam',topic:'Making',time:'Sample Wednesday · 15:00–16:00',ages:'6–10',capacity:6,joined:6,icon:'◇',color:'lilac',about:'Explore structures with cardboard and simple materials. This sample event has a waitlist.'}
];
const pods = [
  {id:'p1',name:'Island curiosity circle',area:'Lamai',focus:'Nature',members:5,max:8,about:'A small caregiver-accompanied circle for nature discoveries and creative afternoons.',initial:'IC',color:'lime'},
  {id:'p2',name:'Stories & little makers',area:'Bophut',focus:'Creative',members:4,max:6,about:'Books, making and a friendly space to try ideas. Plans are agreed by the pod.',initial:'SM',color:'peach'},
  {id:'p3',name:'Build together club',area:'Maenam',focus:'Making',members:6,max:6,about:'A fictional learning pod exploring practical projects and problem-solving.',initial:'BT',color:'lilac'}
];
const polls = [
  {id:'v1',group:'p1',title:'What shall we explore next?',detail:'Help shape the next four sample sessions.',choices:[['nature','Coastal life & nature maps',7],['making','Build a little island village',4],['stories','Our island, our stories',3]]},
  {id:'v2',group:'p1',title:'How should a session feel?',detail:'Choose the rhythm you would find most useful.',choices:[['open','More time for open exploration',5],['guided','A guided project, then free play',8]]},
  {id:'v3',group:'p2',title:'Choose our next shared project',detail:'A sample choice for Stories & little makers.',choices:[['book','Make a shared picture book',6],['puppet','Build a puppet theatre',4]]},
  {id:'v4',group:'class',title:'Which project should our class try?',detail:'A sample class vote, shown separately from pod choices.',choices:[['garden','Design a tiny garden',8],['sound','Create a sound adventure',5],['bridge','Build a paper bridge',4]]}
];
const state = {route:document.body.dataset.page || 'dashboard',filters:{matching:{q:'',area:'All areas',kind:'All approaches'},activities:{q:'',area:'All areas',kind:'All topics'},pods:{q:'',area:'All areas',kind:'All focuses'}},connections:new Set(),joined:new Set(),waitlist:new Set(),podRequests:new Set(),applications:[],votes:{},group:'p1',suggestions:[],quests:new Set()};
const main = document.getElementById('cs-main');
const dialog = document.getElementById('community-dialog');
let restoreFocus = null, noticeTimer;
const esc = value => String(value ?? '').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const urlFor = key => key === 'activities' ? 'activities.html' : key+'.html';
const button = (label,action,id='',extra='') => `<button type="button" class="cs-button ${extra}" data-action="${action}" data-id="${esc(id)}">${label}</button>`;
const link = (label,key,extra='') => `<a class="cs-button ${extra}" href="${urlFor(key)}" data-app-route="${key}">${label}</a>`;
const tag = value => `<span class="cs-tag">${esc(value)}</span>`;
const avatar = (text,color) => `<span class="cs-avatar ${color}" aria-hidden="true">${esc(text)}</span>`;
const empty = (title,detail) => `<div class="cs-empty"><h2>${title}</h2><p>${detail}</p>${button('Clear filters','clear-filters','','outline')}</div>`;
function notify(text){const box=document.getElementById('community-status');box.textContent=text;box.hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>{box.hidden=true;},7000);}
function header(title,description,action='',eyebrow='Your community'){return `<div class="cs-pagehead"><div><div class="cs-eyebrow">${eyebrow}</div><h1>${title}</h1><p>${description}</p></div>${action}</div>`;}
function navigate(route,push=true){
  if(!['dashboard','matching','activities','pods','curriculum','apply','student'].includes(route))return;
  state.route=route;if(push)history.pushState({route},'',urlFor(route));render();main.focus({preventScroll:true});
}
function render(){
  document.body.classList.toggle('cs-student',state.route==='student');
  document.getElementById('community-header').innerHTML=communityHeader(state.route,'',true);
  const renders={dashboard:dashboardView,matching:matchingView,activities:eventsView,pods:podsView,curriculum:votesView,apply:applyView,student:studentView};
  main.innerHTML=renders[state.route]();main.tabIndex=-1;
  document.title={dashboard:'My community',matching:'Find families',activities:'Events',pods:'Pods',curriculum:'Learning votes',apply:'Contribute',student:'Student space'}[state.route]+' · Curriculum Social';
}
function dashboardView(){
  const planned=events.filter(e=>state.joined.has(e.id)||state.waitlist.has(e.id));
  return header('A little community.<br>A world to explore.','Find your people, make a plan and help shape what you learn together.',link('Explore events ↗','activities','light'),'Good to see you')+`<div class="cs-split"><section class="cs-panel"><div class="cs-eyebrow">Your next step</div><h2>Start with one<br>shared experience.</h2><p>Explore sample gatherings, discover a pod or meet families who enjoy the same kinds of learning.</p><div class="cs-actions">${link('Find families','matching')}${link('Explore pods','pods','outline')}</div></section><section class="cs-card"><div class="cs-eyebrow">My sample plan</div><h2>What’s coming up</h2>${planned.length?`<ul class="cs-list">${planned.map(e=>`<li><div><strong>${esc(e.name)}</strong><div class="cs-meta">${state.waitlist.has(e.id)?'Preview waitlist':'Joined in preview'} · ${esc(e.area)}</div></div>${link('View','activities','outline small')}</li>`).join('')}</ul>`:`<p>Your plan is open. Join a sample event to see it here.</p>${link('Find an event','activities','outline')}`}</section></div><h2 class="cs-sectiontitle">Make this your place</h2><div class="cs-grid">${[
    ['Connect','Families who share your curiosity.','Find families','matching','lime','↗'],['Plan','A small group makes room for big ideas.','Start or join a pod','pods','peach','○'],['Choose','Have a say in your pod or class learning.','Explore learning votes','curriculum','lilac','✳']
  ].map(([t,p,l,r,c,i])=>`<section class="cs-card">${avatar(i,c)}<h3>${t}</h3><p>${p}</p><div class="cs-actions">${link(l,r,'outline')}</div></section>`).join('')}</div>`;
}
function toolbar(route,kinds){
  const f=state.filters[route];return `<form class="cs-toolbar" id="filter-form"><div class="cs-field"><label for="search">Search ${route==='matching'?'families':route==='activities'?'events':'pods'}</label><input type="search" id="search" name="q" value="${esc(f.q)}" placeholder="Try nature, music or making"></div><div class="cs-field"><label for="area">Area</label><select id="area" name="area">${['All areas','Lamai','Bophut','Maenam'].map(v=>`<option${f.area===v?' selected':''}>${v}</option>`).join('')}</select></div><div class="cs-field"><label for="kind">${route==='matching'?'Approach':'Focus'}</label><select id="kind" name="kind">${kinds.map(v=>`<option${f.kind===v?' selected':''}>${v}</option>`).join('')}</select></div><button class="cs-button" type="submit">Find my fit ↗</button></form>`;
}
function filtered(records,route,kindField){const f=state.filters[route];return records.filter(r=>(f.area==='All areas'||r.area===f.area)&&(f.kind.startsWith('All ')||r[kindField]===f.kind)&&[r.name,r.about,r.tags?.join(' ')||'',r[kindField]].join(' ').toLowerCase().includes(f.q.trim().toLowerCase()));}
function matchingView(){
  const items=filtered(families,'matching','approach');return header('Find your people.','Start with shared interests and a comfortable pace. Choose who you would like to meet.','<a class="cs-button outline" href="account/profile.html">Edit my profile</a>')+toolbar('matching',['All approaches','Nature & projects','Mixed approaches','Montessori inspired'])+`<p class="cs-result-count">${items.length} sample ${items.length===1?'family':'families'} · Contact details stay private.</p><div class="cs-grid">${items.length?items.map(f=>`<article class="cs-card"><div class="cs-card-top">${avatar(f.initial,f.color)}<div><h3>${esc(f.name)}</h3><div class="cs-meta">${f.area} · Ages ${f.ages}</div></div></div><div class="cs-tags">${f.tags.map(tag).join('')}</div><p>${f.about}</p><div class="cs-meta">${f.approach}</div><div class="cs-actions">${button(state.connections.has(f.id)?'Request drafted ✓':'Say hello ↗','connect',f.id,'small')}${button('Meet this family','family-detail',f.id,'outline small')}</div></article>`).join(''):empty('A little more room to explore.','Try another area or a broader interest.')}</div>`;
}
function eventsView(){
  const items=filtered(events,'activities','topic');return header('Make a little plan.','Simple gatherings, shared discoveries and time together. See the details before you join.',button('Create an event +','create-event','','light'))+toolbar('activities',['All topics','Nature','Creative','Making'])+`<p class="cs-result-count">${items.length} sample events · Dates and availability are illustrative.</p><div class="cs-grid">${items.length?items.map(e=>{const joined=state.joined.has(e.id),waiting=state.waitlist.has(e.id),full=e.joined>=e.capacity;return `<article class="cs-card">${avatar(e.icon,e.color)}<div><div class="cs-meta">${e.time}</div><h2>${esc(e.name)}</h2></div><p>${esc(e.about)}</p><div class="cs-tags">${tag(e.area)}${tag('Ages '+e.ages)}${tag(e.topic)}</div><div class="cs-meta">${Math.max(0,e.capacity-e.joined)} sample places open · Caregiver accompanied</div><div class="cs-actions">${button(joined?'Joined in preview ✓':waiting?'On preview waitlist ✓':full?'Join waitlist ↗':'View & join ↗','event-detail',e.id,joined||waiting?'outline small':'small')}</div></article>`;}).join(''):empty('No gatherings match just yet.','Try fewer filters or draft an event you would like to organize.')}</div>`;
}
function podsView(){
  const items=filtered(pods,'pods','focus');return header('Small circles.<br>Shared possibilities.','A pod is a small group that plans and learns together. Find a fit or propose your own.',button('Start a pod +','create-pod','','light'))+toolbar('pods',['All focuses','Nature','Creative','Making'])+`<p class="cs-result-count">${items.length} sample pods · Joining requires the organizer’s review in a live service.</p><div class="cs-grid">${items.length?items.map(p=>`<article class="cs-card"><div class="cs-card-top">${avatar(p.initial,p.color)}<div><h3>${esc(p.name)}</h3><div class="cs-meta">${esc(p.area)} · ${esc(p.focus)}</div></div></div><p>${esc(p.about)}</p><div class="cs-meta">${p.members} of ${p.max} sample members</div><div class="cs-actions">${button(state.podRequests.has(p.id)?'Request drafted ✓':'Explore this pod ↗','pod-detail',p.id,'small')}${button('Learning choices','pod-votes',p.id,'outline small')}</div></article>`).join(''):empty('Your circle could start here.','Try a different area or propose a small pod.')}</div>`;
}
function votesView(){
  const groupPolls=polls.filter(p=>p.group===state.group);return header('A voice in<br>what comes next.','Choose a pod or class, explore the options and make your preference count. You can change your vote.',button('Suggest an idea +','suggest','','light'))+`<div class="cs-toolbar" style="grid-template-columns:1fr auto"><div class="cs-field"><label for="vote-group">Your pod or class</label><select id="vote-group">${[...pods.map(p=>[p.id,p.name]),['class','Sample learning class']].map(([id,name])=>`<option value="${id}"${state.group===id?' selected':''}>${name}</option>`).join('')}</select></div><p class="cs-quiet">Sample tally · One preference per question.</p></div><div class="cs-grid two">${groupPolls.length?groupPolls.map(p=>{const total=p.choices.reduce((n,c)=>n+c[2],0)+(state.votes[p.id]?1:0);return `<article class="cs-card"><div class="cs-eyebrow">Learning choice · Open in preview</div><h2>${p.title}</h2><p>${p.detail}</p><div>${p.choices.map(([id,label,count])=>{const chosen=state.votes[p.id]===id,number=count+(chosen?1:0);return `<div class="cs-choice"><div style="flex:1"><strong>${label}</strong><div class="cs-meta">${number} sample votes · ${Math.round(number/total*100)}%</div><div class="cs-progress" aria-hidden="true"><span style="width:${Math.round(number/total*100)}%"></span></div></div><button class="cs-button outline small" type="button" data-action="vote" data-id="${p.id}" data-choice="${id}" aria-pressed="${chosen}">${chosen?'Your choice ✓':'Choose'}</button></div>`;}).join('')}</div><p class="cs-votestate">${state.votes[p.id]?'Your preview preference is included. Choosing another option replaces it.':'Explore the options, then choose the one you prefer.'}</p></article>`;}).join(''):`<div class="cs-empty"><h2>A fresh page for your ideas.</h2><p>This sample group has no open learning vote yet. Suggest an idea to start the conversation.</p>${button('Suggest an idea','suggest','','outline')}</div>`}</div>${state.suggestions.filter(s=>s.group===state.group).length?`<h2 class="cs-sectiontitle">Ideas you suggested</h2><div class="cs-grid">${state.suggestions.filter(s=>s.group===state.group).map(s=>`<article class="cs-card"><h3>${esc(s.title)}</h3><p>${esc(s.detail)}</p><span class="cs-tag">Draft idea · Not sent</span></article>`).join('')}</div>`:''}<p class="cs-quiet" style="margin-top:24px">Voting informs planning. A live educator or organizer still checks feasibility and participation needs. Preview votes do not approve a curriculum or event.</p>`;
}
function applyView(){return header('Bring what<br>you care about.','Choose a contribution that fits your skills and time. A clear next step makes it easier to get involved.', '', 'Find your place')+`<div class="cs-grid">${[
  ['Educator','Guide a shared discovery.','Propose a hands-on learning experience and tell us about your experience and availability.','teach','peach','✳'],
  ['Venue host','Make room for community.','Describe a potential space, facilities and availability for a small learning gathering.','venue','lime','⌂'],
  ['Contributor','A little help, well placed.','Offer a concrete skill or task: community welcome, making resources or practical coordination.','contribute','lilac','↗']
].map(([role,t,p,id,c,i])=>`<article class="cs-card">${avatar(i,c)}<div class="cs-eyebrow">${role}</div><h2>${t}</h2><p>${p}</p><div class="cs-actions">${button('Explore & apply ↗','apply',id)}</div></article>`).join('')}</div><p class="cs-quiet" style="margin-top:20px">Applications require review. Submitting a draft does not grant access, confirm employment or verify a venue or educator.</p>${state.applications.length?`<h2 class="cs-sectiontitle">Your application drafts</h2><div class="cs-grid">${state.applications.map(a=>`<article class="cs-card"><span class="cs-tag">${esc(a.role)} · Draft</span><h3>${esc(a.name)}</h3><p>${esc(a.offer)}</p><p class="cs-meta">${esc(a.availability)}</p></article>`).join('')}</div>`:''}`;}
function studentView(){return header('Hello, explorer.<br>What will you discover?','Pick a small offline adventure. Share an idea with your grown-up and help choose what your group explores next.',link('Choose our next project ✳','curriculum','light').replace('data-app-route="curriculum"','data-app-route="curriculum" data-group="class"'),'Student space · Sample adventures')+`<div class="cs-split"><section class="cs-panel"><div class="cs-eyebrow">Today’s little adventure</div><h2>Find three things<br>that make you wonder.</h2><p>A leaf, a sound, a shadow? Step outside with your grown-up. Draw what you find, then ask one big question.</p><div class="cs-actions">${button(state.quests.has('wonder')?'Adventure marked ✓':'I tried it ✳','quest','wonder')}</div></section><section class="cs-card"><div class="cs-eyebrow">Your curiosity trail</div><h2>Little discoveries count.</h2><div class="cs-stat">${state.quests.size}</div><p>Sample adventures you marked in this tab. Take your time. No streaks, scores or pressure to keep clicking.</p>${link('Share a learning idea','curriculum','outline')}</section></div><h2 class="cs-sectiontitle">Pick a path</h2><div class="cs-grid">${[
 ['build','◇','Make a tiny bridge','Use paper and a few small blocks. What shape makes your bridge stronger?','peach'],['story','✎','Tell a little story','Draw an imaginary island. Who lives there, and what do they need?','lilac'],['nature','☀','Notice your neighborhood','Look for three different leaf shapes with your grown-up. What is the same?','lime']
].map(([id,i,t,p,c])=>`<article class="cs-card">${avatar(i,c)}<h3>${t}</h3><p>${p}</p><div class="cs-actions">${button(state.quests.has(id)?'Marked as tried ✓':'I tried it','quest',id,'outline')}</div></article>`).join('')}</div><p class="cs-quiet" style="margin-top:22px">Explore with a caregiver. Use suitable materials and choose an activity that feels comfortable. This preview has no student account, uploads or child records.</p>`;}

function openDialog(title,body,trigger){restoreFocus=trigger;document.getElementById('dialog-title').textContent=title;document.getElementById('dialog-body').innerHTML=body;dialog.showModal();const first=dialog.querySelector('input,select,textarea');(first||dialog.querySelector('.cs-close')).focus();}
function closeDialog(){dialog.close();restoreFocus?.focus();}
const field=(id,label,type='text',placeholder='',required=true)=>`<div class="cs-field"><label for="${id}">${label}</label>${type==='textarea'?`<textarea id="${id}" name="${id}" maxlength="800"${required?' required':''} placeholder="${placeholder}"></textarea>`:`<input id="${id}" name="${id}" type="${type}" maxlength="120"${required?' required':''} placeholder="${placeholder}">`}</div>`;
const select=(id,label,options)=>`<div class="cs-field"><label for="${id}">${label}</label><select id="${id}" name="${id}">${options.map(o=>`<option>${o}</option>`).join('')}</select></div>`;
const form=(kind,id,fields,submit)=>`<form id="action-form" data-kind="${kind}" data-id="${esc(id)}">${fields}<p class="cs-formerror" id="form-error" role="alert" hidden></p><div class="cs-notice">Preview only. Use sample details. This creates a draft in this tab; nothing is sent.</div><div class="cs-actions"><button type="submit" class="cs-button">${submit}</button><button type="button" class="cs-button outline" data-action="close">Cancel</button></div></form>`;
function action(kind,id,trigger){
  if(kind==='clear-filters'){state.filters[state.route]={q:'',area:'All areas',kind:state.route==='matching'?'All approaches':state.route==='activities'?'All topics':'All focuses'};render();document.getElementById('search')?.focus();return;}
  if(kind==='close'){closeDialog();return;}
  if(kind==='pod-votes'){state.group=id;navigate('curriculum');return;}
  if(kind==='quest'){state.quests.has(id)?state.quests.delete(id):state.quests.add(id);render();notify('Your sample curiosity trail is updated. Time to explore away from the screen.');return;}
  if(kind==='vote'){const p=polls.find(p=>p.id===id),choice=trigger.dataset.choice;if(!p||p.group!==state.group||!p.choices.some(c=>c[0]===choice))return;state.votes[id]=choice;render();main.querySelector(`[data-id="${id}"][data-choice="${choice}"]`)?.focus();notify('Your preview choice is recorded. You can change it any time.');return;}
  if(kind==='family-detail'){const f=families.find(f=>f.id===id);openDialog(f.name,`<p>${esc(f.about)}</p><div class="cs-tags">${f.tags.map(tag).join('')}</div><p class="cs-quiet">${f.area} · Ages ${f.ages} · ${f.approach}</p><div class="cs-notice">Sample family. No private contact details are shown.</div><div class="cs-actions" style="margin-top:20px">${button('Draft a hello ↗','connect',id)}</div>`,trigger);return;}
  if(kind==='connect'){const f=families.find(f=>f.id===id);openDialog('Say hello',`<p class="cs-quiet">To ${f.name} · A little context helps start a connection.</p>`+form('connect',id,field('message','What would you like to explore together?','textarea','A nature walk, music or a little creative project…'),'Create request draft ↗'),trigger);return;}
  if(kind==='event-detail'){const e=events.find(e=>e.id===id),joined=state.joined.has(id),waiting=state.waitlist.has(id),full=e.joined>=e.capacity;openDialog(e.name,`<p>${esc(e.about)}</p><div class="cs-tags">${tag(e.area)}${tag('Ages '+e.ages)}${tag(e.topic)}</div><p class="cs-quiet">${e.time} · Caregiver accompanied. Sample places: ${e.capacity-e.joined}.</p>`+(joined||waiting?`<div class="cs-notice">${waiting?'You are on the preview waitlist.':'You joined this event in the preview.'} Nothing was sent.</div><div class="cs-actions" style="margin-top:20px">${button('Leave sample plan','leave-event',id,'outline')}</div>`:form('join-event',id,`<label><input type="checkbox" id="ack" name="ack" required> I understand a caregiver accompanies the family for this sample gathering.</label>`,full?'Join preview waitlist ↗':'Join in preview ↗')),trigger);return;}
  if(kind==='leave-event'){if(state.joined.delete(id)){events.find(e=>e.id===id).joined--;}state.waitlist.delete(id);closeDialog();render();notify('Removed from your sample plan.');return;}
  if(kind==='pod-detail'){const p=pods.find(p=>p.id===id);openDialog(p.name,`<p>${esc(p.about)}</p><div class="cs-tags">${tag(p.area)}${tag(p.focus)}${tag(p.members+' of '+p.max+' sample members')}</div>`+form('join-pod',id,field('message','What makes this pod a fit?','textarea','Tell the sample organizer what you would enjoy…'),p.members>=p.max?'Draft interest for next opening ↗':'Draft a join request ↗'),trigger);return;}
  if(kind==='create-event'){openDialog('Create a gathering',form('create-event','',field('name','Event name','text','A clear, friendly name')+`<div class="cs-formgrid">${select('area','Area',['Lamai','Bophut','Maenam'])}${select('topic','Focus',['Nature','Creative','Making'])}</div>`+field('date','Proposed date','date')+field('about','What will people do?','textarea','Describe the experience and caregiver participation…')+field('capacity','Family places','number','2–20'),'Create event draft ↗'),trigger);dialog.querySelector('#date').min=new Date().toISOString().slice(0,10);dialog.querySelector('#capacity').min='2';dialog.querySelector('#capacity').max='20';dialog.querySelector('#capacity').step='1';return;}
  if(kind==='create-pod'){openDialog('Start a little pod',form('create-pod','',field('name','Pod name','text','A name for your circle')+`<div class="cs-formgrid">${select('area','Area',['Lamai','Bophut','Maenam'])}${select('focus','Shared focus',['Nature','Creative','Making'])}</div>`+field('about','What will you learn or do together?','textarea','Give people a clear picture of your group…')+field('max','Maximum adult members','number','2–12'),'Create pod draft ↗'),trigger);dialog.querySelector('#max').min='2';dialog.querySelector('#max').max='12';dialog.querySelector('#max').step='1';return;}
  if(kind==='suggest'){openDialog('A new learning idea',form('suggest',state.group,field('name','Idea title','text','What would you like to explore?')+field('about','Why this idea?','textarea','Explain the activity and what the group could discover…'),'Save idea draft ↗'),trigger);return;}
  if(kind==='apply'){const title={teach:'Offer a learning experience',venue:'Offer a community space',contribute:'Offer a contribution'}[id];openDialog(title,form('apply',id,field('name','Your sample name','text','Sample Adult')+field('email','Sample contact email','email','sample@example.invalid')+field('offer',id==='teach'?'Experience and proposed session':id==='venue'?'Space, facilities and suitability':'A specific skill or task','textarea','Describe what you can offer…')+field('availability','Your realistic availability','text','For example: a few hours each month'),'Save application draft ↗'),trigger);}
}
function submitAction(formElement){
  const error=document.getElementById('form-error');error.hidden=true;
  const data=Object.fromEntries(new FormData(formElement).entries());
  if(!formElement.checkValidity()||[...formElement.querySelectorAll('[required]:not([type=checkbox])')].some(el=>!el.value.trim())){error.textContent='Please complete the required fields with a little detail.';error.hidden=false;return;}
  const kind=formElement.dataset.kind,id=formElement.dataset.id;
  if(kind==='connect'){state.connections.add(id);}
  else if(kind==='join-event'){const e=events.find(e=>e.id===id);if(!e||state.joined.has(id)||state.waitlist.has(id))return;if(e.joined>=e.capacity)state.waitlist.add(id);else{state.joined.add(id);e.joined++;}}
  else if(kind==='join-pod'){state.podRequests.add(id);}
  else if(kind==='create-event'){const capacity=Number(data.capacity);if(!Number.isInteger(capacity)||capacity<2||capacity>20){error.textContent='Choose between 2 and 20 family places.';error.hidden=false;return;}events.unshift({id:'draft-event-'+events.length,name:data.name.trim(),area:data.area,topic:data.topic,time:'Draft · '+data.date,ages:'To agree',capacity,joined:0,icon:'✳',color:'lime',about:data.about.trim()});state.filters.activities={q:'',area:'All areas',kind:'All topics'};}
  else if(kind==='create-pod'){const max=Number(data.max);if(!Number.isInteger(max)||max<2||max>12){error.textContent='Choose between 2 and 12 adult members.';error.hidden=false;return;}pods.unshift({id:'draft-pod-'+pods.length,name:data.name.trim(),area:data.area,focus:data.focus,members:1,max,about:data.about.trim(),initial:'P',color:'lime'});state.filters.pods={q:'',area:'All areas',kind:'All focuses'};}
  else if(kind==='suggest'){state.suggestions.push({group:id,title:data.name.trim(),detail:data.about.trim()});}
  else if(kind==='apply'){state.applications.push({role:{teach:'Educator',venue:'Venue host',contribute:'Contributor'}[id],name:data.name.trim(),offer:data.offer.trim(),availability:data.availability.trim()});}
  closeDialog();render();main.focus({preventScroll:true});notify(kind==='join-event'?'Your sample plan is updated. No booking or message was sent.':'Your preview draft is saved in this tab. Nothing was sent.');
}
document.addEventListener('click',event=>{
  const routeLink=event.target.closest('[data-app-route]');if(routeLink){if(event.ctrlKey||event.metaKey||event.shiftKey||event.altKey)return;event.preventDefault();if(routeLink.dataset.group)state.group=routeLink.dataset.group;navigate(routeLink.dataset.appRoute);return;}
  const trigger=event.target.closest('[data-action]');if(trigger)action(trigger.dataset.action,trigger.dataset.id,trigger);
});
document.addEventListener('submit',event=>{
  if(event.target.id==='filter-form'){event.preventDefault();state.filters[state.route]=Object.fromEntries(new FormData(event.target).entries());render();document.getElementById('search')?.focus();}
  if(event.target.id==='action-form'){event.preventDefault();submitAction(event.target);}
});
document.addEventListener('change',event=>{if(event.target.id==='vote-group'){state.group=event.target.value;render();document.getElementById('vote-group').focus();}});
dialog.querySelector('.cs-close').addEventListener('click',closeDialog);
dialog.addEventListener('cancel',()=>{restoreFocus?.focus();});
window.addEventListener('popstate',()=>{const key=location.pathname.split('/').pop().replace(/\.html$/,'');navigate(key,false);});
render();
