const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {JSDOM,VirtualConsole}=require('jsdom');
const root=path.resolve(__dirname,'../..');
const source=fs.readFileSync(root+'/review/community-app.js','utf8').replace(/^import .*;\n/m,'');
const shell=fs.readFileSync(root+'/js/community-shell.js','utf8').replace('export function','function');
let passed=0;
function setup(page='dashboard'){
 const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
 const html=fs.readFileSync(root+'/review/community-app.html','utf8').replace('data-page="dashboard"',`data-page="${page}"`);
 const dom=new JSDOM(html,{runScripts:'outside-only',url:'https://example.invalid/'+page+'.html',virtualConsole:vc});
 const w=dom.window,d=w.document;w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};
 for(const name of ['fetch','XMLHttpRequest'])w[name]=()=>{throw Error('Unexpected network');};
 w.eval(shell+'\n'+source);
 return {dom,w,d,errors,click(selector){d.querySelector(selector).click();},submit(id){d.getElementById(id).dispatchEvent(new w.Event('submit',{cancelable:true,bubbles:true}));},fill(id,value){d.getElementById(id).value=value;},route(key){d.querySelector(`[data-app-route="${key}"]`).click();}};
}
function test(name,fn){const x=setup();try{fn(x);assert.deepEqual(x.errors,[]);passed++;console.log('PASS '+name);}finally{x.dom.window.close();}}
test('one shell and current-page navigation across seven screens',x=>{
 for(const r of ['matching','activities','pods','curriculum','apply','student','dashboard']){x.route(r);assert.equal(x.d.querySelectorAll('.cs-header').length,1);assert.equal(x.d.querySelector('.cs-appnav [aria-current=page]').dataset.appRoute,r);assert(x.d.querySelector('h1'));}
});
test('family filters have empty/reset states and preserve search',x=>{x.route('matching');x.fill('area','Lamai');x.fill('kind','Nature & projects');x.submit('filter-form');assert.match(x.d.querySelector('.cs-result-count').textContent,/2 sample/);x.fill('search','no-such-topic');x.submit('filter-form');assert(x.d.querySelector('.cs-empty'));x.click('[data-action=clear-filters]');assert.equal(x.d.querySelectorAll('.cs-card').length,4);});
test('connection drafts require meaningful text and clearly state nothing sent',x=>{x.route('matching');x.click('[data-action=connect]');x.fill('message','   ');x.submit('action-form');assert(x.d.querySelector('dialog').open);assert(!x.d.getElementById('form-error').hidden);x.fill('message','A sample nature walk.');x.submit('action-form');assert(!x.d.querySelector('dialog').open);assert.match(x.d.querySelector('[data-action=connect]').textContent,/drafted/);assert.match(x.d.getElementById('community-status').textContent,/Nothing was sent/);});
test('event join, repeat protection, plan visibility and leaving',x=>{x.route('activities');x.click('[data-action=event-detail][data-id=e1]');x.submit('action-form');assert(!x.d.getElementById('form-error').hidden);x.d.getElementById('ack').checked=true;x.submit('action-form');assert.match(x.d.querySelector('[data-id=e1]').textContent,/Joined/);x.click('[data-action=event-detail][data-id=e1]');assert(!x.d.getElementById('action-form'));x.click('.cs-close');x.route('dashboard');assert.match(x.d.getElementById('cs-main').textContent,/Joined in preview/);x.route('activities');x.click('[data-action=event-detail][data-id=e1]');x.click('[data-action=leave-event]');assert.match(x.d.querySelector('[data-id=e1]').textContent,/View & join/);});
test('full events offer a waitlist',x=>{x.route('activities');x.click('[data-id=e3]');assert.match(x.d.querySelector('#action-form button[type=submit]').textContent,/waitlist/);x.d.getElementById('ack').checked=true;x.submit('action-form');assert.match(x.d.querySelector('[data-id=e3]').textContent,/waitlist/);});
test('event creation validates capacity and renders user text safely',x=>{x.route('activities');x.click('[data-action=create-event]');x.fill('name','<img src=x onerror=alert(1)>');x.fill('about','Synthetic event only.');x.fill('date','2030-01-01');x.fill('capacity','1');x.submit('action-form');assert(x.d.querySelector('dialog').open);x.fill('capacity','8');x.submit('action-form');assert.match(x.d.querySelector('.cs-card h2').textContent,/<img/);assert.equal(x.d.querySelectorAll('.cs-card img').length,0);});
test('pod drafts, request flow and group-specific learning views',x=>{x.route('pods');x.click('[data-action=create-pod]');x.fill('name','Synthetic pod');x.fill('about','A shared creative idea.');x.fill('max','4');x.submit('action-form');assert.match(x.d.querySelector('.cs-card h3').textContent,/Synthetic pod/);x.click('[data-action=pod-detail]');x.fill('message','We would enjoy this sample group.');x.submit('action-form');assert.match(x.d.querySelector('[data-action=pod-detail]').textContent,/drafted/);x.click('[data-action=pod-votes]');assert.match(x.d.querySelector('.cs-empty').textContent,/no open learning vote/);});
test('one replaceable vote per question with group isolation',x=>{x.route('curriculum');x.click('[data-id=v1][data-choice=nature]');assert.equal(x.d.querySelectorAll('[data-id=v1][aria-pressed=true]').length,1);x.click('[data-id=v1][data-choice=making]');assert.equal(x.d.querySelectorAll('[data-id=v1][aria-pressed=true]').length,1);assert.equal(x.d.querySelector('[data-id=v1][data-choice=making]').getAttribute('aria-pressed'),'true');x.fill('vote-group','p2');x.d.getElementById('vote-group').dispatchEvent(new x.w.Event('change',{bubbles:true}));assert.equal(x.d.querySelectorAll('[data-id=v1]').length,0);x.fill('vote-group','p1');x.d.getElementById('vote-group').dispatchEvent(new x.w.Event('change',{bubbles:true}));assert.equal(x.d.querySelector('[data-id=v1][data-choice=making]').getAttribute('aria-pressed'),'true');});
test('suggestions are scoped and safely rendered',x=>{x.route('curriculum');x.click('[data-action=suggest]');x.fill('name','<script>sample</script>');x.fill('about','A synthetic idea.');x.submit('action-form');assert.match(x.d.querySelector('#cs-main').textContent,/<script>sample/);assert.equal(x.d.querySelectorAll('#cs-main script').length,0);});
test('applications require contact, offer and availability; grant no access',x=>{x.route('apply');x.click('[data-action=apply][data-id=teach]');x.fill('name','Sample Adult');x.fill('email','invalid');x.fill('offer','Sample offer');x.fill('availability','One hour a month');x.submit('action-form');assert(x.d.querySelector('dialog').open);x.fill('email','sample@example.invalid');x.submit('action-form');assert.match(x.d.querySelector('#cs-main').textContent,/Your application drafts/);assert.match(x.d.getElementById('community-status').textContent,/Nothing was sent/);});
test('student space is playful, reversible, offline and routes to class choices',x=>{x.route('student');assert(x.d.body.classList.contains('cs-student'));x.click('[data-id=wonder]');assert.equal(x.d.querySelector('.cs-stat').textContent,'1');x.click('[data-id=wonder]');assert.equal(x.d.querySelector('.cs-stat').textContent,'0');x.click('[data-app-route=curriculum][data-group=class]');assert.equal(x.d.getElementById('vote-group').value,'class');assert(!x.d.body.classList.contains('cs-student'));});
test('dialog cancel restores focus and no network/storage implementation',x=>{x.route('matching');const trigger=x.d.querySelector('[data-action=connect]');trigger.focus();trigger.click();x.click('.cs-close');assert.equal(x.d.activeElement,trigger);assert(!/\b(fetch|XMLHttpRequest|localStorage|sessionStorage)\s*[.(]/.test(source));});
console.log(passed+' community scenario groups passed; native dialogs adapted, no browser rendering');
